### DISCUSSION TITLE
Full Width Links In Sidebar

### DISCUSSION THREAD

**Discussion by fweth** [UniMath/SymmetryBookFormalization#1081] [General]
Just a minor thing, but I don't like how the links in the sidebar are only as wide as the text, resulting in shorter words creating smaller clickable areas. This seems to fix it:

```css
.chapter li > a {
  flex-grow: 1;
}
.chapter li > a.toggle {
  margin-left: 0;
  flex-grow: 0;
  ```

Can do a pull request if you like.
